### ISSUE TITLE
no router for /api/posts

### ISSUE THREAD

**Issue by mjtk-ktjm** [awslabs/amazon-ecs-nodejs-microservices#5]
navigating to /api/posts fails since there is no router configured for it in server.js
This is as compared to /api/users and /api/threads which return all users and all threads respectively.
Additionally, the tutorial actually recommends testing api and posts services using that url.

The fix is easy...add this to ./3-microservices/services/server.js and /2-containerized/services/api/server.js
```node
router.get('/api/posts', function *() {
  this.body = db.posts;
});
```
I have done this in a fork (as well as correcting a spelling error).

**Comment by nathanpeck** [comment]
Merged thanks!
